export const carActions = {
    GET_CARS_DATA: 'GET_CARS_DATA',
    GET_CARS_DATA_SUCCESS: 'GET_CARS_DATA_SUCCESS',
    SHOW_CARS_DATA: 'SHOW_CARS_DATA',
    GET_CARS_DATA_FAILURE: 'GET_CARS_DATA_FAILURE',
    DISPLAY_GET_CARS_DATA_FAILURE_MESSEGE: 'DISPLAY_GET_CARS_DATA_FAILURE_MESSEGE',
    ADD_CAR_TO_SHOPPING_CART: 'ADD_CAR_TO_SHOPPING_CART',
    REMOVE_CAR_FROM_SHOPPING_CART: 'REMOVE_CAR_FROM_SHOPPING_CART',
    SEARCH_CAR_FIELD_CHANGED: 'SEARCH_CAR_FIELD_CHANGED'
};
