export const carActions = {
    GET_CARS_DATA: 'GET_CARS_DATA',
    GET_CARS_DATA_SUCCESS: 'GET_CARS_DATA_SUCCESS',
    SHOW_CARS_DATA: 'SHOW_CARS_DATA',
    GET_CARS_DATA_FAILURE: 'GET_CARS_DATA_FAILURE'
};
