export const loginActions = {
    GET_USER_INFO: 'GET_USER_INFO',
    GET_USER_INFO_FAILURE: 'GET_USER_INFO_FAILURE',
    LOGIN: 'LOGIN',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    DISPLAY_LOGIN_FAILURE_MESSEGE: 'DISPLAY_LOGIN_FAILURE_MESSEGE'
};
